###channel-artifacts is no room to place, however bind it to the orderer is an good idea
apiVersion: apps/v1
# apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fabrick8s
  name: orderer0-orgorderer1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orderer0-orgorderer1
  template:
    metadata:
      labels:
        name: orderer0-orgorderer1
    spec:
      hostAliases:
      # - ip: "127.0.0.1"
        # hostnames:
        # - "orderer0.orgorderer1"
      containers:
      - name: orderer0-orgorderer1
        image: hyperledger/fabric-orderer
        env:
        - name: TZ
          value: "America/Chicago"
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "32000"
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: Orgorderer1MSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/var/hyperledger/orderer/tls/ca.crt]'
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        # ports:
         # - containerPort: 32000 #7050
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp 
           name: certificate
           subPath: orderers/orderer0.orgorderer1/msp
         - mountPath: /var/hyperledger/orderer/tls
           name: certificate
           subPath: orderers/orderer0.orgorderer1/tls
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: certificate
           subPath: genesis.block
      volumes:
       - name: certificate
         persistentVolumeClaim:
             claimName: orgorderer1-pv


---
apiVersion: v1
kind: Service
metadata:
  name: orderer0-orgorderer1
  namespace: fabrick8s
spec:
 selector:
   name: orderer0-orgorderer1
 type: NodePort
 ports:
   - name: grpc
     protocol: TCP
     port: 32000
     targetPort: 32000
     nodePort: 32000
